### ISSUE TITLE
Server extensions not added for function policies

### ISSUE THREAD

**Issue by devinivy** [mark-bradshaw/mrhorse#26]
Currently if you use mrhorse only with function policies, they are not applied.  Only when you create a policy _file_ using a particular apply point does that apply point become active.  This is the crucial line that is not run: https://github.com/mark-bradshaw/mrhorse/blob/master/lib/index.js#L220

**Comment by mark-bradshaw** [comment]
Thanks for mentioning this.  So I looked it over and it doesn't seem like an easy/natural fix.  The handlers aren't attached to the various life cycle events unless we know that we have policies that need it.  I'm not sure if there's a great way to proceed.  We could have an option to the registration that forces a handler to be attached to a lifecycle event, but you'd have to manually keep it up.  We could try to parse through the routes looking for function policies, but that assumes the routes are already there when mrhorse is registered.  No guarantees there.  I guess we could listen for the 'start' event on the server, since all routes should be in place by then.

**Comment by devinivy** [comment]
Yes, it seems like a good place to do a lot of this work might be in `onPreStart`.  Some sort of "compile" step could run through the routing table.

**Comment by devinivy** [comment]
Oops– looks like we talked about this here! https://github.com/mark-bradshaw/mrhorse/issues/22
