### ISSUE TITLE
Function applyPoint does not work when no normal policies are available

### ISSUE THREAD

**Issue by microcipcip** [mark-bradshaw/mrhorse#38]
I think I have found a bug. 

I am using mrHorse mainly with dynamic functions, and I have discovered that when there are no normal policies available in the `policies` folder with the same `applyPoint` as the dynamic functions, the `applyPoint` within the dynamic functions does not work.

Here is a very simple repo to [showcase the error](https://github.com/microcipcip/mrhorse_with_functions). If you run the code as is, it will correctly print:
```
pre handler policy
pre handler policy function
hello world
post handler policy
post handler policy function
```

However, is I remove the `policies/postHandler`, it will print the following:
```
pre handler policy function
hello world
```
Intead of this:
```
pre handler policy function
hello world
post handler policy function
```

I can easily fix this error by creating a fake normal policy with the hook I need, I just wanted to report this issue so that others are aware of it.

**Comment by mark-bradshaw** [comment]
Thank you.  I'll take a look.

**Comment by mark-bradshaw** [comment]
Thanks for the heads up on this one.  Apparently this is a bit of an odd use case because anyone doing only dynamic functions would've hit this issue.  Basically it comes down to how we add our handlers to the Hapi life cycle hooks.  In order not to burden Hapi unnecessarily we only bind to a life cycle hook if we have a policy that requires it.  However, with dynamic only routes we don't get to have that information when the plugin registers.  We never bind to any life cycle hooks, and so the policies never run.

To account for this scenario I've added a plugin register option called `watchApplyPoints`, that gives MrHorse a hint about what life cycle hooks you are going to use.  You need to supply an array of strings that match the apply points you want, and MrHorse will go ahead and bind to those if it hasn't already.  

Like this:
```
await server.register({
        plugin: require('mrhorse'),
        options: {
            watchApplyPoints: ['onPreHandler', 'onPostHandler']
        }
    });
```

That should do you.  It's live now as version 3.0.1.  And yeah, I realize now that should've been 3.1, but it's late and published and I'm just going to roll with it.

**Comment by microcipcip** [comment]
@mark-bradshaw Thanks a lot, amazing support :)
