### ISSUE TITLE
Any way to OR

### ISSUE THREAD

**Issue by tjsail33** [mark-bradshaw/mrhorse#5]
Is there any way to OR two policies? Say I have two policies isAdmin and isServerAdmin, and certain routes I want to be accessible to both, but certain routes should be restricted to just one.

**Comment by mark-bradshaw** [comment]
In cases like that I have another policy that incorporates that OR'ing and use that.  So for instance I'd have another policy called isServerAdminButNotAdmin, or isAdminOrServerAdmin.  It's wordy, but it gets the point across.  It's ok to duplicate yourself in order to express your policies clearly.  I'd recommend adding some quick unit tests for these simple policies to make sure they always do what you want.
