### ISSUE TITLE
Are policies guaranteed to execute in order?

### ISSUE THREAD

**Issue by tjsail33** [mark-bradshaw/mrhorse#6]
Say I have one policy called isLoggedIn and then one policy called isUsingMac. If i pass them to mrhorse using `policies: ['isLoggedIn','isUsingMac']`, do these policies execute in order, parallel, or random?

**Comment by mark-bradshaw** [comment]
They execute in order.  If any of the policies callback with false the chain of policies will stop there, and no more policies will be run.  The idea is to be as efficient as reasonably possible, and that means failing early and skipping policy runs.  I use policies for authorization, data loading, and logging.  I try to do authorization early on so that I can skip data loads for requests that will get 401s.
