### ISSUE TITLE
validation before mrhorse

### ISSUE THREAD

**Issue by PavelPolyakov** [mark-bradshaw/mrhorse#9]
I have some validation configured together with my route:
```
"saveClientData": {
    "path"      : "",
    "method"    : ["POST"],
    "handler"   : "save",
    "validation": true,
    "filter"    : true,
    "config"    : {
      "plugins": {
        "policies": ["user-with-app"]
      }
    }
  }
```

And, I see that validation takes place before the mrhorse. If the validation passes, but policy does not - then we see the expected result.

I don't think it's logical. Do we have any way to put the mrhorse infront?

Regards,

**Comment by mark-bradshaw** [comment]
@PavelPolyakov This is due to the [hapi request lifecycle](http://hapijs.com/api#request-lifecycle).  MrHorse hooks into the pre and post handler.  As you can see from the lifecycle the authentication parts happen before the prehandler parts.  The good news is that MrHorse can easily be extended to support the other lifecycle points where Hapi sends out an event.

For your purposes, if you want a policy to run before authentication you could use the `onRequest` or `onPreAuth` events.  My inclination would be to use the latest event you can use that still gets the policy run before authentication.  That would be `onPreAuth`.

In MrHorse the code to modify would be in lib/index.js.  You would add another block of code similar to lines 94-103.  Just change the event that it's hooking into from onPostHandler to onPreAuth.  You'd also want to add tests to keep coverage at 100% if you intend to contribute code back to MrHorse.  That, of course, would be appreciated.

**Comment by PavelPolyakov** [comment]
@mark-bradshaw 
Thanks, would try that approach!

**Comment by mark-bradshaw** [comment]
This is being addressed in a PR. https://github.com/mark-bradshaw/mrhorse/pull/10
